---
# Absolute path for local files
local_path: '/Users/jason/PycharmProjects/bq-nvd/'

# GCS bucket that will be used for storing NVD json files and
# BQ newline delimited json load files
bucket_name: 'redteam_bq-nvd'

# BigQuery project and dataset names
project: 'red-team-project'
dataset: 'nvd_test'

# Relative path to BigQuery NVD dataset schema
nvd_schema: './schema.json'

# NVD URL base
url_base: 'https://nvd.nist.gov/feeds/json/cve/1.1/'

# NVD file prefix
file_prefix: 'nvdcve-1.1-'

# NVD file suffix
file_suffix: '.json.gz'